# -*- coding: utf-8 -*-
# this file is generated by gen_kdata_schema function, dont't change it
from zvt.schemas.quotes.block.block_1d_kdata import *
from zvt.schemas.quotes.block.block_1wk_kdata import *
from zvt.schemas.quotes.block.block_1mon_kdata import *